### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by GGWPXXXX** [ssahibsingh/GoogleFormsAutomation#1]
I'm tryna use this code but this error occurred.

C:\Users\uSEr\main.py:7: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome('C:\webdrivers\chromedriver.exe')
Traceback (most recent call last):
  File "C:\Users\uSEr\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\uSEr\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\uSEr\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\uSEr\main.py", line 7, in <module>
    driver = webdriver.Chrome('C:\webdrivers\chromedriver.exe')
  File "C:\Users\uSEr\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\uSEr\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 90, in __init__
    self.service.start()
  File "C:\Users\uSEr\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

**Comment by ssahibsingh** [comment]
Have you installed chromedriver or Chrome Webdriver on your system?
If you have installed it then update the path in line 7 
i.e.
driver = webdriver.Chrome('Update the path here')

**Comment by GGWPXXXX** [comment]
Ok Thanks.
